backend:
  name: git-gateway
  repo: Gitrua07/art-website   # replace with your GitHub username and repo
  branch: main                    # branch to commit to
  auth_type: implicit             # uses GitHub login

media_folder: "images"           # folder in repo for uploaded images
public_folder: "/images"

collections:
  - name: "artworks"
    label: "Artworks"
    slug: "{{slug}}"
    file: "artworks/artworks.json"
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Me"
        name: "about"
        file: "content/about.json"
        format: json
        fields:
          - {label: "About Me", name: "about me", widget: "text"}
